### ISSUE TITLE
 small issue

### ISSUE THREAD

**Issue by cike-567** [doanhmaple/Razer-Blade-15-Advanced-2018-Hackintosh#1]
I used your efi, I used opencore to boot windows10 and ACPI BIOS ERROR appeared. I get an error when compiling SSDT-HPET (25, 6160, One or more prefix Scopes do not exist (\_SB.PCI0.LPCB.HPET._CRS)), this ssdt is not a must, I can still use it normally after I remove it The sound card has crashes during use, which may be related to this. SSDT-PNLFCFL has a warning (25, 3073, Multiple types (Device object requires either a _HID or _ADR, but not both)). The usb customization is not very good. The usb on the left side of my notebook cannot be used normally. Your ssdt is not well written, and it will affect other systems. OC-little is recommended.

**Comment by doanhxd** [comment]
Sorry for the bad experience when using my efi... I've been updated the most stable EFI of researching carefully. Thanks for your recommended.
