### ISSUE TITLE
Thunderbolt is not working

### ISSUE THREAD

**Issue by wizzeng** [doanhmaple/Razer-Blade-15-Advanced-2018-Hackintosh#3]
![image](https://user-images.githubusercontent.com/37865213/89805313-0a0e1c00-db68-11ea-814e-0885b87ffe5e.png)

**Comment by wizzeng** [comment]
4K display can only run at 1440P. No 2160P option avaliable.

**Comment by doanhxd** [comment]
Hmmm... I was make a newest EFI and add TB3 SSDT to try to fix it, you can try again... I don't have any TB3 device to test it, only Type-C to HDMI cable to use FHD discrete display... and please don't try to change other SMBIOS, just stay at MBP15,2 it's the most stable for RB15 Advanced (2018-2019)... Thanks for using my EFI 👍 :v

**Comment by wizzeng** [comment]
OK, I will try that later.

**Comment by doanhxd** [comment]
> OK, I will try that later.

https://www.displaylink.com/downloads/macos
can you try this for your 4K display?... i found this when trying to patch tb3 port... hope it can help you.../

**Comment by wizzeng** [comment]
> > OK, I will try that later.
> 
> https://www.displaylink.com/downloads/macos
> can you try this for your 4K display?... i found this when trying to patch tb3 port... hope it can help you.../

Thanks, I will check it out.

**Comment by wizzeng** [comment]
4k display doesn't work with new EFI. Only 1440P available.
