### ISSUE TITLE
Thunderbolt EGPU

### ISSUE THREAD

**Issue by shiecldk** [doanhmaple/Razer-Blade-15-Advanced-2018-Hackintosh#5]
Hi does thunderbolt egpu work with your setup? I have RZ09-02386 (GTX1070) with your EFI files; everything works excpet thunderbolt. I have tried to set Thunderbolt Security level to No Security in BIOS with menu unlocked; however, I still have no luck with it. I also found these could be helpful: https://www.tonymacx86.com/threads/in-progress-ssdt-for-thunderbolt-3-hotplug.248784/
https://www.tonymacx86.com/threads/guide-how-to-use-egpu-with-any-laptop-equipped-with-thunderbolt-3.283179/post-2010533

**Comment by ghost** [comment]
Thunderbolt eGPU work just fix the port
