### ISSUE TITLE
No Camera 

### ISSUE THREAD

**Issue by darkloki19** [doanhmaple/Razer-Blade-15-Advanced-2018-Hackintosh#7]
The camera is not working on mine. 

![](https://i.ibb.co/WG7T9pF/Screen-Shot-2021-03-04-at-1-07-09-PM.png)

![](https://i.ibb.co/4tB9X96/Screen-Shot-2021-03-04-at-1-07-19-PM.png)

**Comment by darkloki19** [comment]
Everything else for me though works great! Thanks!

**Comment by doanhxd** [comment]
does your camera work on Windows? if not then it'll never work on macOS, please use your brain

**Comment by darkloki19** [comment]
It does work in windows want the screenshot. Why would you assume I’m that dumb what the fuck ?

________________________________

**Comment by doanhxd** [comment]
try to learn how to Map USB Ports :D 
https://github.com/corpnewt/USBMap

**Comment by doanhmaple** [comment]
I've notice in README... 
Never read but always ask many dumb question, god bless you

**Comment by doanhxd** [comment]
you've asked about Camera since March 5, now is April 3 but not fixed yet? Why people never try to learn, try to read but always try to ask many fucking dumb question?

**Comment by darkloki19** [comment]
________________________________

**Comment by doanhxd** [comment]
I have notice about USB Map in my README? Why not read?

**Comment by darkloki19** [comment]
Fuck you dude I hope you have a nice Dick Salad and Dick Ham on Easter Sunday. Eat Shit and die motherfucker.You must not get laid to be all grump ass, Go Get Bent...

**Comment by doanhmaple** [comment]
god bless you <3

**Comment by doanhmaple** [comment]
Thank you for your best wishes, but please take those words to yourself <3

**Comment by doanhxd** [comment]
Thank you for your best wishes, but you can save those words for yourself <3

**Comment by darkloki19** [comment]
How's this for Camera working for you? 
![D1ckWad](https://user-images.githubusercontent.com/67139906/113479154-51308080-945b-11eb-8215-6988d3c0e93d.JPG)

**Comment by doanhxd** [comment]
I thought you could fix it in the hackintosh, :))) haha, NOOB, oh my god, i've never met anyone as STUPID as you in my life!!!!!
God may sad about you if you keep talking to people with those words :( I hope he will still believe and bless you.

**Comment by darkloki19** [comment]
> does your camera work on Windows? if not then it'll never work on macOS, please use your brain

Whose stupid, can you not recall your own questions, your memory is like non-existant and look who started attacking.

**Comment by doanhxd** [comment]
i just tell you to use your brain before asking any question. you're the one who start the war

**Comment by darkloki19** [comment]
Anyways it's 6AM for me I'm going back to sleep, you on the other hand I suggest you get bent. You can't even properly speak enlglish, your broken english is all over this thread.

**Comment by doanhxd** [comment]
sleep well <3

**Comment by doanhxd** [comment]
Thank you <3 but you'll still the stupidest person I've ever met in my life <3 Thank you
stupid but always saying bad words to people, OMG

**Comment by darkloki19** [comment]
The original Screneshots in the first post shows that I did the Read Me and the install. The Hackintosh works fine other then the Camera Working. Doing a USB Mapping does what for Camera. We're past that point...

**Comment by doanhxd** [comment]
doing USB Map will remap your device's usb ports and your camera will work well with it :D I've notice about it before but never READ

**Comment by darkloki19** [comment]
Says nothing about the Camera in the Read Me.

**Comment by doanhxd** [comment]
Camera work well for me, but I always suggest people to Re-map their USB Ports, you never want to learn how to Hackintosh but try to attack me?

**Comment by darkloki19** [comment]
If it's Asssumed that you do the USB MAP which will fix the Camera then it's AssUMe meaning you make an Ass out of Yourself and ME

**Comment by darkloki19** [comment]
Okay about this whole attacking me, go to your employer or customer in real life and tell them to "Use your Brain" and let me know how that actually works for in you real life....

**Comment by doanhxd** [comment]
That's because my EFI has USBPorts.kext, you see? That's the problem because every device is different even if it's the same model

**Comment by darkloki19** [comment]
If I said "Use your Brain" to my aging mother I'd get smacked and I'm not even joking.

**Comment by doanhxd** [comment]
Sorry for my bad words

**Comment by darkloki19** [comment]
Sorry for my outburst, it's something that I was caught off guard and too defensive.

**Comment by doanhxd** [comment]
i can take remote desktop to do the usb map for you

**Comment by darkloki19** [comment]
I got it thank you, though, I appreciate the offer and kind gesture.
